---
title: "Introduction"
---

# Introduction {#intro}

This course provides PhD candidates with the essential knowledge and the core skills to manage research data according to best practice. You will be able to integrate good data management practices within your workflow from the beginning of your projects. The application of this knowledge to your research will allow you to reflect on how to work efficiently and in a reproducible manner with your research data, while complying with funders and institutional requirements.

## Relevant dates:

**Course start:** 21 February (Survey + Importance of RDM)

**In person session:** 29 February

## Learning Objectives:

After completing this course, you will be able to:

-   Realise the important role that good data management plays in research

-   Identify different types of research data and recognise the regulations, policies and/or legal requirements associated with them.

-   List the main components of the FAIR data principles and connect them to your own research workflows.

-   Employ the acquired knowledge to design an efficient research data management strategy for your projects according to best practices.

## Code of Conduct

-   Everyone is learning, including instructors - please have patience and respect towards each other!
-   Use welcoming and inclusive language when interacting with your peers and instructors
-   Be respectful of different viewpoints and experiences
-   Provide and gracefully accept constructive criticism

If at any point you're confronted with undesirable behaviour, please reach out to the trainer or Francisca.

## In person session

<table style="width:98%;">
<colgroup>
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 9%" />
</colgroup>
<thead>
<tr class="header">
<th><p>Topic</p></th>
<th><p>Time (s)</p></th>
<th><p>Time (e)</p></th>
<th><p>Duraction</p></th>
<th><p>Comments?</p></th>
<th><p></p></th>
<th><p></p></th>
<th><p></p></th>
<th><p></p></th>
<th><p></p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>Introductions</p></td>
<td><p>9:00</p></td>
<td><p>9:20</p></td>
<td><p>20 min</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>Why is RDM important</p></td>
<td><p>9:20</p></td>
<td><p>9:40</p></td>
<td><p>20 min</p></td>
<td><p><strong>Discussion:</strong> Do you find the horror stories or the benefits more convincing? <br />
Do you have a horror story to share?<br />
What is your main challenge in Data Management?</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><p>RDM essentials</p></td>
<td><p>9:40</p></td>
<td><p>10:10</p></td>
<td><p>30 min</p></td>
<td><p><strong>Discussion:</strong> what is your challenge? (15 min)</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>Break</p></td>
<td><p>10:10</p></td>
<td><p>10:35</p></td>
<td><p>15 min</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><p>FAIR principles</p></td>
<td><p>10:35</p></td>
<td><p>10:45</p></td>
<td><p>10 min</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>FAIR: licences</p></td>
<td><p>10:45</p></td>
<td><p>11:00</p></td>
<td><p>15 min</p></td>
<td><p><strong>Exercise:</strong> choose a license</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><p>FAIR: organisation</p></td>
<td><p>11:00</p></td>
<td><p>11:30</p></td>
<td><p>30 min</p></td>
<td><p><strong>Exercise</strong>: look at data organisation/naming and what to improve</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>Questions?</p></td>
<td><p>11:30</p></td>
<td><p>11:45</p></td>
<td><p>15 min</p></td>
<td><p>If no questions, discuss what challenges are left to address.</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><p>Lunch</p></td>
<td><p>12:00</p></td>
<td><p>13:00</p></td>
<td><p>60 min</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>FAIR: documentation</p></td>
<td><p>13:00</p></td>
<td><p>13:40</p></td>
<td><p>40 min</p></td>
<td><p><strong>Exercise:</strong> set up a readme file and check with someone else</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><p>FAIR: publication</p></td>
<td><p>13:40</p></td>
<td><p>14:10</p></td>
<td><p>30 min</p></td>
<td><p><strong>Exercise:</strong> Check which data repository or data/software journal to use - at the end summarise which data repositories/journals are used</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>Break</p></td>
<td><p>14:10</p></td>
<td><p>14:25</p></td>
<td><p>15 min</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><p>Setting up your DMP</p></td>
<td><p>14:25</p></td>
<td><p>15:25</p></td>
<td><p>60 min</p></td>
<td><p><strong>Exercise</strong>: use ERC template to set up the plan</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>Break</p></td>
<td><p>15:25</p></td>
<td><p>15:45</p></td>
<td><p>15 min</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><p>Exchanging DMP</p></td>
<td><p>15:45</p></td>
<td><p>16:15</p></td>
<td><p>30 min</p></td>
<td><p><strong>Exercise:</strong> Exchange DMP to receive feedback</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>Wrap up discussion</p></td>
<td><p>16:15</p></td>
<td><p>16:35</p></td>
<td><p>20 min</p></td>
<td><p><strong>Discussion:</strong> What topic of the course challenged you the most? And why?<br />
What theme challenged you the least because you were already implementing RDM best practices before this course? (If any)<br />
What do you want to implement from the course?</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><p>Wrap up</p></td>
<td><p>16:35</p></td>
<td><p>16:45</p></td>
<td><p>10 min</p></td>
<td><p>Summarise day<br />
Ask feedback<br />
Potential next steps</p></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
