---
title: "Policies"
bibliography: references.bib
---

# Applicable Policies

In this module, we present an overview of the policies you will need to adhere to as a PhD candidate at IMPRS-QBEE. At the end of this module you should be able to:

-   Realise what policies are applicable to you
-   Recognise the responsibilities regarding RDM

## IMPRS-QBEE requirements

Regulations of the International Max Planck Research School for Quantitative Behavior Ecology and Evolution from lab to field (9 March 2023, [pdf](https://imprs-qbee.mpg.de/65696/EN_Regulations_IMPRS-QBEE.pdf))

**Section 4: Scientific results and publications**

1.  In accordance with the rules of scientific practice of the Max Planck Society, the position paper of the German Rectors' Conference (HRK) on good scientific practice at German universities and institutions, and the guidelines for safeguarding good scientific practice of the German Research Foundation (DFG), **all primary data must be reliably secured and kept at the site for 10 years; this also includes the clear and comprehensive documentation of the methods used (laboratory notebook/lab book) and all important results. This obligation also includes data that do not support a hypothesis or lead to a publication. The project leader or the researcher is responsible for research data management and thus for the proper preparation, backup and storage of research data**. Support is provided by the Research Data Management Services of the U KN and the Max Planck Digital Library.

2.  **Documents** such as copies of the lab book, funding applications, manuscripts (and also revisions of manuscripts) and abstracts for conferences **may only be taken along with the explicit approval of the direct supervisor after completion of the doctoral procedure**.

## [Konstanz University Open Science policy](https://www.kim.uni-konstanz.de/en/openscience/open-science-policy/)

The University of Konstanz is **committed to the principles of Open Science** and takes its social responsibility as a scientific institution seriously. Open Science consists of strategies and pro-cedures that make all elements of the scientific process openly accessible, transparent and usable for others. ...Open Science activities are rec-ognised as a characteristic of good scientific work.

Generally, **the project leader or researcher is responsible** for ensuring compliance with this policy.

When publishing **research works, data or other research results** as well as teaching materials and other resources, the University of Konstanz recommends ensuring they are available per-manently. This can be achieved through licencing under free **licences** (for example, Creative Commons). Open Science is handled in accordance with legal framework conditions, for example on data protection, foreign trade law, the protection of persons and personal rights as well as intellec-tual property and other asset rights. Ethical issues and any contractual obligations must also be taken into account.

#### Open Science policy: Research Data

Research data are all data that are created, employed, or discovered in the context of scientific and scholarly research. They are available in different formats and types. **At the University of Konstanz, we view the publication of research data as part of the research process**. University of Konstanz researchers are required to prepare, save, document and store research data in accordance with relevant subject-specific standards. This also includes documentation of the methods and tools used. **We recommend the FAIR Principles as a guideline**. We ask our researchers, as far as permissible and reasonable, to **make research data publicly available at the earliest possible time in the form of a citable data publication, with the aim of keeping it accessible, verifiable and reusable in the long term and independent from the data producer.** **Please use a suitable, trustworthy data repository or data archive for the publication.** We will provide supporting infrastructure and advisory services.

#### Open Science policy: Free software

The University of Konstanz **recommends publishing software developed at the university under a free licence.** When using software for research purposes, the university recommends checking whether appropriate free software is available.

## Max Planck Society Policy ([**pdf**](https://urldefense.com/v3/__https://www.mpg.de/197494/rulesScientificPractice.pdf__;!!PAKc-5URQlI!4R3UgXaRpqFOu5I-_TtX5LxphA1Hg3LMDPxzqh84lc-KDU_bM11zZTF1mhBVj07d7XkyA3ZiwhVrndW4usJ5JFoQ$)**)**

2.3 Research standards

-   Scientifically founded, **reproducible methods** applied with scientific probity are an **essential condition of all scientific work**. These already include identifying the origin of any data, organisms, materials and software used in the research process and providing evidence for their later use.

-   The source code of publicly accessible software must be persistent, citable and documented.

2.4 Securing and storing primary data – Documentation and archiving

-   The duration of retention periods …. is normally **10 years**.

-   Research Group Leaders and individual researchers are obligated to make use of the protection options provided by Institute Management and retain and store both research data and research results. It does not matter in this context whether the research results are published or not. Even inconclusive results and examinations must be documented.

-   The Research Group Leaders must select the corresponding data together with Institute Management and the Archives of the Max-Planck-Gesellschaft.

-   In most cases, **only a selection of research data is worth retaining** (clarification of suitability and eligibility for archiving).

2.7 Accessibility of research data

-   For reasons of traceability, follow-on research and potential later use, **scientists store the research data and central materials on which the publication is based whenever possible – following the FAIR principles** … – e.g. in accessible, commonly recognized archives and repositories.

-   “In individual cases, **there can be reasons not to make the data publicly accessible**. For example, the purpose of the scientist’s own research must not be negatively impacted and there must be no justified concerns regarding potential misuse of the data. In any case, any legal requirements which conflict with any transfer of research data (e.g. preservation of intellectual property rights, data protection) take precedence.

## [Regulations of the DFG](https://wissenschaftliche-integritaet.de/en/code-of-conduct/) (Deutsche Forschungsgemeinschaft)

**Guideline 13: Providing public access to research results**

-   \[..\] If it has been decided to make results available in the public domain, researchers describe them clearly and in full. Where possible and reasonable, this includes **making the research data, materials and information on which the results are based, as well as the methods and software used, available** and fully explaining the work processes. \[..\] (<https://doi.org/10.5281/zenodo.3923601>, p. 17)

**Guideline 17: Archiving**

-   When scientific and academic findings are made publicly available, t**he research data (generally raw data) on which they are based are generally archived** in an accessible and identifiable manner for a period of ten years at the institution where the data were produced or in cross-location repositories. (<https://doi.org/10.5281/zenodo.3923601>, p. 20)

For this reason, the [DFG expects research projects](www.dfg.de/proposal_process/research_data) to include a description of how research data is handled. The description should be based on the **checklist for handling research data** (to [the questionnaire](https://www.dfg.de/download/pdf/foerderung/grundlagen_dfg_foerderung/forschungsdaten/forschungsdaten_checkliste_en.pdf)).

1.  Data description

2.  Documentation and data quality

3.  Storage and technical archiving the project

4.  Legal obligations and conditions

5.  Data exchange and long-term data accessibility

6.  Responsibilities and resources

**The description of how research data will be handled is included in the review** and also forms part of the reporting obligation after completion of the project.

## European Commission / Horizon Europe projects

-   Proposals: one page explaining how data (and other research outputs) will be managed in line with the **FAIR principles**

-   Once funding is awarded (within 6 months): Horizon Europe data management plan ([download](https://enspire.science/wp-content/uploads/2021/09/Horizon-Europe-Data-Management-Plan-Template.pdf) template)

-   **Data underpinning the publications should be shared through a trusted repository at the time of publication.**

-   Data is **in principle open**, unless restricted access is needed for legitimate reasons 

    -   Legitimate reasons: privacy, public security, ethical limitations, property rights and commercial interest.

-   Data should be licensed using CC-BY or CC0 (or equivalent), and metadata should be CC0. 

    -   For [CC-BY](https://creativecommons.org/licenses/by/4.0/) it means that others should cite the work when they reuse the data. 

    -   [CC0](https://creativecommons.org/publicdomain/zero/1.0/) waives any rights, with citation still being expected as this follows best scientific practises.

## Summary of Requirements

-   Data/code underlying publications should be shared **in accordance with FAIR principles** in data repositories

    -   There can be reasons not to make the data publicly accessible (preservation of intellectual property rights, data protection)

-   All primary data must be reliably **secured for 10 years**, including metadata/documentation

-   A **checklist or plan** on how to handle research data is advisable
