project:
  type: website
  output-dir: docs
  
website:
  title: "RDM 101"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01-introduction.qmd
      - 02-Importance-RDM.qmd
      - 03-Essentials-RDM.qmd
      - 05-Policies-RDM.qmd
      - 05-FAIR.qmd
      - 06-Organisation.qmd
      - 07-Documentation.qmd
      - 08-Publication.qmd
      - 09-DMP.qmd
      - 10-Next.qmd
    tools:
      - icon: github
        href: https://github.com/EstherPlomp/DRA-RDM-1
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "RDM101"

format:
  html:
    theme: cerulean
    toc: true

editor: source

